# Generated by Django 4.2.7 on 2023-12-01 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('auther', models.CharField(max_length=70)),
                ('book_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('auther_photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('price_day_rent', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('period_rent', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rental', 'rental'), ('solid', 'solid')], max_length=90, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.category')),
            ],
        ),
    ]
