# Generated by Django 4.2.7 on 2023-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_total_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=7),
        ),
    ]
